{
 "title": "Weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outdoor Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", tempf FROM sensor_data ORDER BY \"time\" DESC LIMIT 1 "
    },
    {
     "rawSql": "SELECT \"time\", feels_like FROM sensor_data ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Outdoor Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", humidity FROM sensor_data ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", windspeedmph FROM sensor_data ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 14, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", winddir FROM sensor_data ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", tempinf FROM sensor_data ORDER BY \"time\" DESC LIMIT 1 "
    },
    {
     "rawSql": "SELECT \"time\", feels_likein FROM sensor_data ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Indoor Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", humidityin FROM sensor_data ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Wind Gust",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", windgustmph FROM sensor_data ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Temperature / Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", windspeedmph FROM sensor_data ORDER BY \"time\" DESC "
    },
    {
     "rawSql": "SELECT \"time\", tempf FROM sensor_data ORDER BY \"time\" DESC "
    }
   ]
  },
  {
   "title": "Windrose",
   "type": "operato-windrose-panel",
   "gridPos": { "h": 15, "w": 6, "x": 11, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\",\n  winddir as wind_direction,\n  windspeedmph as wind_speed\nFROM\n  sensor_data\nORDER BY time desc\nLIMIT 2000;"
    }
   ]
  }
 ]
}